<div class="col-md-4 col-md-offset-4">
    <div class="panel panel-default">
        <?php
        if (isset($params["nepavyko_prisijungti"])) {
            echo '<div class="alert alert-warning alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong>Prisijungti nepavyko!</strong> ' . $params["nepavyko_prisijungti"] . '.</div>';
        }
        ?>
        <div class="panel-heading">
            <h3 class="panel-title">
                <strong>Administratoriaus prisijungimas</strong>
            </h3>
        </div>
        <div class="panel-body">
            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="prisijungimas">Prisijungimo vardas</label>
                    <input type="text" class="form-control" style="border-radius:0px" id="prisijungimas" name="prisijungimas" placeholder="Įveskite prisijungimo vardą" />
                </div>
                <div class="form-group">
                    <label for="slaptazodis">Slaptažodis</label>
                    <input type="password" class="form-control" style="border-radius:0px" id="slaptazodis" name="slaptazodis" placeholder="Slaptažodis" />
                </div>
                <button type="submit" class="btn btn-sm btn-default">Prisijungti</button>
            </form>
        </div>
    </div>
</div>

